fig, axarr = plt.subplots(2, 2, figsize=(12, 18))
df.groupby('album')['popularity'].mean().sort_values(ascending=False).plot.bar(ax=axarr[0][0], fontsize=12)
axarr[0][0].set_title("album Vs popularity", fontsize=18)
df.groupby('release_date')['popularity'].mean().sort_values(ascending=False).plot.bar(ax=axarr[0][1], fontsize=12)
axarr[0][1].set_title("release_date Vs popularity", fontsize=18)
df.groupby('duration_ms')['popularity'].mean().sort_values(ascending=False).head(10).plot.bar(ax=axarr[1][0], fontsize=12)
axarr[1][0].set_title("duration_ms Vs popularity", fontsize=18)
df.groupby('tempo')['popularity'].mean().sort_values(ascending=False).head(10).plot.bar(ax=axarr[1][1], fontsize=12)
axarr[1][1].set_title("tempo Vs popularity", fontsize=18)
plt.subplots_adjust(hspace=1.0)
plt.subplots_adjust(wspace=.5)
